### ISSUE TITLE
Error with chromedriver on scraping

### ISSUE THREAD

**Issue by commarla** [mattbostock/navigation_timing_exporter#1]
Hi,

Thanks for your work on this exporter. I got this error when I tried to curl this url `curl http://localhost:9156/probe\?target\=https://prometheus.io/` : 

`ERRO[0024] failed to retrieve URL: unexpected response: {"sessionId":"9a00b5ced6cfe589a2252bb67544e545","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.22.397932 (282ed7cf89cf0053b6542e0d0f039d4123bbb6ad),platform=Linux 3.16.0-4-amd64 x86_64)"}}  source=probe.go:45`

I am using the latest chromedriver http://chromedriver.storage.googleapis.com/index.html?path=2.22/ and I have built your exporter with GO 1.6.2.

Do you know what happen? I have zero knowledge of chromedriver :D

Regards,

Laurent

**Comment by commarla** [comment]
Maybe I need Xvfb. I should have read the readme.

**Comment by commarla** [comment]
I also have an error on my mac with : 

`ERRO[0036] failed to run script: unexpected response: {"sessionId":"acc66d616b5043208ed9d91c0e1084b4","status":0,"value":{"connectEnd":1468266125271,"connectStart":1468266125271,"domComplete":1468266126349,"domContentLoadedEventEnd":1468266125856,"domContentLoadedEventStart":1468266125701,"domInteractive":1468266125700,"domLoading":1468266125491,"domainLookupEnd":1468266125271,"domainLookupStart":1468266125271,"fetchStart":1468266125271,"loadEventEnd":1468266126350,"loadEventStart":1468266126349,"navigationStart":1468266125039,"redirectEnd":0,"redirectStart":0,"requestStart":1468266125293,"responseEnd":1468266125489,"responseStart":1468266125488,"secureConnectionStart":0,"toJSON":{},"unloadEventEnd":0,"unloadEventStart":0}}  source=probe.go:56`

**Comment by mattbostock** [comment]
Thanks for reporting. It seems this issue may occur with recent versions of Chrome; I've been able to reproduce it locally. I'll have a fix shortly.

**Comment by mattbostock** [comment]
@commarla Please try with the most recent version, 0.0.3.

**Comment by commarla** [comment]
:+1: thanks
