### ISSUE TITLE
Useful recording rules

### ISSUE THREAD

**Issue by syepes** [mattbostock/navigation_timing_exporter#2]
Hello Matt,
Just wanted to mention that this project is awesome!
I was starting to writing something similar but in Ruby, are you going to continue the dev on this?

Is there any plans on removing the redirect limitation (Requires exact URL as target)?

Here are some recording rules that I am currently using:

```
# Web Official https://www.w3.org/TR/navigation-timing/
instance:web:backEnd:seconds = navigation_timing_response_start_seconds{job="webdriver"} - navigation_timing_start_seconds{job="webdriver"}
instance:web:domContentLoaded:seconds = navigation_timing_dom_content_loaded_event_start_seconds{job="webdriver"} - navigation_timing_start_seconds{job="webdriver"}
instance:web:domInteractive:seconds = navigation_timing_dom_interactive_seconds{job="webdriver"} - navigation_timing_start_seconds{job="webdriver"}
instance:web:domainLookup:seconds = navigation_timing_domain_lookup_end_seconds{job="webdriver"} - navigation_timing_domain_lookup_start_seconds{job="webdriver"}
instance:web:frontEnd:seconds = navigation_timing_load_event_start_seconds{job="webdriver"} - navigation_timing_response_end_seconds{job="webdriver"}
instance:web:pageDownload:seconds = navigation_timing_response_end_seconds{job="webdriver"} - navigation_timing_response_start_seconds{job="webdriver"}
instance:web:pageLoad:seconds = navigation_timing_load_event_start_seconds{job="webdriver"} - navigation_timing_start_seconds{job="webdriver"}
instance:web:redirection:seconds = navigation_timing_fetch_start_seconds{job="webdriver"} - navigation_timing_start_seconds{job="webdriver"}
instance:web:serverConnection:seconds = navigation_timing_connect_end_seconds{job="webdriver"} - navigation_timing_connect_start_seconds{job="webdriver"}

# Web Other
instance:web:latency:seconds = navigation_timing_response_start_seconds{job="webdriver"} - navigation_timing_fetch_start_seconds{job="webdriver"}
instance:web:transfer:seconds = navigation_timing_response_end_seconds{job="webdriver"} - navigation_timing_response_start_seconds{job="webdriver"}
instance:web:domProcessingInteractive:seconds = navigation_timing_dom_interactive_seconds{job="webdriver"} - navigation_timing_dom_loading_seconds{job="webdriver"}
instance:web:domProcessingComplete:seconds = navigation_timing_dom_complete_seconds{job="webdriver"} - navigation_timing_dom_interactive_seconds{job="webdriver"}
instance:web:onLoad:seconds = navigation_timing_load_event_end_seconds{job="webdriver"} - navigation_timing_load_event_start_seconds{job="webdriver"}
```

By the way, I made this all work in a docker container if your interested I could share the setup

**Comment by mattbostock** [comment]
Thanks! I'm not using this exporter myself currently but will continue development if others find it useful as you have.

I chose to require an exact URL for two reasons, first because it makes the code simpler but more importantly because it guarantees the exact URL that you're testing. If you could provide some more information about your use case, I'd be happy to reconsider.

Thanks for sharing the recording rules, would you be happy to raise a pull request to add them to the README? I'd prefer snake case rather than camel case, in the format:

```
instance:navigation_timing_domain_lookup_seconds
```

**Comment by syepes** [comment]
@mattbostock Thanks for the reply, the use case is relatively simple: Monitor websites availability and response time like with blackbox_exporter but with the full time decomposition not just response times.
The most important feature IMHO that's currently missing is some thing like blackbox_exporter  (fail_if_matches_regexp or fail_if_not_matches_regexp) to actually verify that the actual expected site loaded and not just the proxy loading page for example...

No problem,  I will send a PR with the recording rules using recording rules.

Regards,
Sebastian

**Comment by mattbostock** [comment]
Thanks @syepes.

I'm still not sure I understand the requirement to follow redirects; if you're monitoring a website, you would know the URL to test in advance. Is there a different use case you have that I'm misunderstanding?

I'd gladly accept a PR that allows you to verify the existence of a string on the page, similar to `fail_if_matches_regexp`.

**Comment by syepes** [comment]
@mattbostock Sorry, I forgot the redirects issue, well its not really a problem its just that some sites I am using redirect us to a specific page from the main URL, http://www.example.com/ -> http://www.example.com/es/

The workaround is just to specify the final URL, but it could be interesting in some cases just to follow the redirects.

**Comment by mattbostock** [comment]
Recording rules added in #3.

I think that by default it makes sense to require an exact URL to help guarantee you're testing the URL you specified, but if there's enough demand for it with good use cases I'm happy to reconsider.

Thanks again for the contribution @syepes.
